apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: viewer-all-namespaces-binding
subjects:
  - kind: ServiceAccount
    name: dashboard-viewer-access
    namespace: jp
roleRef:
  kind: ClusterRole
  name: viewer-all-namespaces
  apiGroup: rbac.authorization.k8s.io
